variables:
- group: Azure Data
- group: Azure Key Vault


trigger: none

stages: 

# Validate
- stage: Validate
  displayName: Validate
  jobs:
    - job: validate
      pool:
        vmImage: ubuntu-latest

      steps:
      - task: TerraformInstaller@0
        inputs:
          terraformVersion: 'latest'

      - task: AzureKeyVault@2
        inputs:
          azureSubscription: $(subscription_id)
          KeyVaultName: $(azure_key_vault)
          SecretsFilter: '*'
          RunAsPreJob: false

      - task: TerraformCLI@0
        displayName: Initialize Terraform
        inputs:
          command: 'init'
          backendType: 'azurerm'
          allowTelemetryCollection: true

      - task: TerraformCLI@0
        displayName: Validate of Terraform config
        inputs:
          command: 'validate'
          allowTelemetryCollection: true

# Plan
- stage: Plan
  displayName: Plan
  jobs:
  - job: plan
    pool:
      vmImage: ubuntu-latest

    steps:
    - task: TerraformInstaller@0
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'

    - task: AzureKeyVault@2
      inputs:
        azureSubscription: $(subscription_id)
        KeyVaultName: $(azure_key_vault)
        SecretsFilter: '*'
        RunAsPreJob: false
    - task: TerraformCLI@0
      displayName: Initialize Terraform
      inputs:
        command: 'init'
        backendType: 'azurerm'
        allowTelemetryCollection: true
    - task: TerraformCLI@0
      displayName: Plan Terraform Deployment
      env:
        ARM_CLIENT_ID: $(clientID)
        ARM_CLIENT_SECRET: $(clientsecret)
        ARM_SUBSCRIPTION_ID: $(subscription_id])
        ARM_TENANT_ID: $(tenantID)
      inputs:
        command: 'plan'
        environmentServiceName: $(subscription_id)
        allowTelemetryCollection: true

# Approve
- stage: Approve
  displayName: Approve
  jobs:
  - job: approve
    displayName: Wait for approval
    pool: server
    steps: 
    - task: ManualValidation@0
      timeoutInMinutes: 60
      inputs:
        notifyUsers: 'ned@nedinthecloud.com'
        instructions: 'Review the plan in the next hour'